# Generated by Django 3.1.7 on 2021-03-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='login.user')),
                ('temp', models.CharField(max_length=16)),
                ('locat', models.CharField(max_length=32)),
                ('locations', models.CharField(max_length=256)),
                ('level', models.CharField(max_length=4)),
                ('info', models.BooleanField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
